export const mockPatientInput = {
  patient_id: 'PAT-2024-0042',
  name: 'Lakshmi Devi',
  age: 58,
  gender: 'Female',
  vitals: {
    heart_rate: 112,
    blood_pressure_systolic: 168,
    blood_pressure_diastolic: 95,
    temperature: 37.2,
    spo2: 93,
  },
  symptoms: ['Chest pain', 'Shortness of breath', 'Palpitations', 'Dizziness'],
  medical_history: ['Hypertension', 'Diabetes Mellitus Type 2'],
};

export const mockClassificationResult = {
  risk_level: 'HIGH',
  confidence: 0.89,
  ml_risk_assessment: 'HIGH',
  triage_category: 'URGENT',
  key_factors: [
    'Elevated heart rate (112 bpm) with chest pain',
    'Hypertension with BP 168/95',
    'SpO2 at 93% indicates mild hypoxemia',
    'History of Diabetes increases cardiovascular risk',
  ],
};

export const mockSpecialistOpinions = [
  {
    specialty: 'Cardiology',
    relevance_score: 0.95,
    urgency_score: 0.88,
    confidence: 0.91,
    one_liner: 'Acute coronary syndrome must be ruled out given chest pain with tachycardia and hypertension.',
    claims_primary: true,
    flags: [
      { severity: 'RED_FLAG', label: 'Possible ACS', description: 'Chest pain + tachycardia + risk factors' },
    ],
    assessment: 'Patient presents with classic anginal symptoms. Elevated HR and BP suggest sympathetic activation. Immediate ECG and troponin required. Consider dual antiplatelet therapy if ACS confirmed.',
    differentials: [
      { condition: 'Acute Coronary Syndrome', probability: 0.45 },
      { condition: 'Unstable Angina', probability: 0.30 },
      { condition: 'Hypertensive Emergency', probability: 0.15 },
      { condition: 'Aortic Dissection', probability: 0.10 },
    ],
    recommended_workup: [
      { test: '12-Lead ECG', priority: 'STAT', rationale: 'Rule out STEMI/NSTEMI' },
      { test: 'Troponin I/T', priority: 'STAT', rationale: 'Cardiac biomarker assessment' },
      { test: 'Chest X-Ray', priority: 'URGENT', rationale: 'Assess cardiac silhouette and pulmonary status' },
      { test: 'Complete Blood Count', priority: 'URGENT', rationale: 'Baseline hematology' },
    ],
  },
  {
    specialty: 'Neurology',
    relevance_score: 0.55,
    urgency_score: 0.45,
    confidence: 0.72,
    one_liner: 'Dizziness could indicate vertebrobasilar insufficiency; low suspicion for acute stroke.',
    claims_primary: false,
    flags: [
      { severity: 'YELLOW_FLAG', label: 'Dizziness with HTN', description: 'Monitor for neurological deterioration' },
    ],
    assessment: 'Dizziness likely secondary to cardiovascular compromise rather than primary neurological event. No focal deficits reported. Recommend monitoring and neuro consult if symptoms persist after cardiac stabilization.',
    differentials: [
      { condition: 'Vertebrobasilar insufficiency', probability: 0.25 },
      { condition: 'Peripheral vertigo', probability: 0.20 },
    ],
    recommended_workup: [
      { test: 'Neurological examination', priority: 'URGENT', rationale: 'Assess for focal deficits' },
    ],
  },
  {
    specialty: 'Pulmonology',
    relevance_score: 0.72,
    urgency_score: 0.68,
    confidence: 0.78,
    one_liner: 'SpO2 93% with dyspnea warrants pulmonary evaluation to rule out PE or pulmonary edema.',
    claims_primary: false,
    flags: [
      { severity: 'YELLOW_FLAG', label: 'Mild Hypoxemia', description: 'SpO2 93% needs monitoring' },
    ],
    assessment: 'Borderline hypoxemia with shortness of breath. Could be secondary to cardiac failure or primary pulmonary pathology. D-dimer recommended to rule out PE. Supplemental O2 to maintain SpO2 > 95%.',
    differentials: [
      { condition: 'Pulmonary Edema', probability: 0.35 },
      { condition: 'Pulmonary Embolism', probability: 0.20 },
      { condition: 'COPD Exacerbation', probability: 0.10 },
    ],
    recommended_workup: [
      { test: 'ABG Analysis', priority: 'STAT', rationale: 'Quantify respiratory compromise' },
      { test: 'D-Dimer', priority: 'URGENT', rationale: 'Rule out PE' },
      { test: 'Chest X-Ray', priority: 'URGENT', rationale: 'Assess lung fields' },
    ],
  },
  {
    specialty: 'Emergency Medicine',
    relevance_score: 0.90,
    urgency_score: 0.92,
    confidence: 0.88,
    one_liner: 'High-acuity presentation requiring immediate stabilization and rapid workup.',
    claims_primary: false,
    flags: [
      { severity: 'RED_FLAG', label: 'Multi-system involvement', description: 'Cardiac + respiratory compromise simultaneously' },
    ],
    assessment: 'This patient needs immediate resuscitation bay placement. IV access, continuous monitoring, and rapid diagnostic workup. Activate chest pain protocol. Consider early cardiology consult.',
    differentials: [
      { condition: 'ACS', probability: 0.40 },
      { condition: 'Hypertensive Emergency', probability: 0.25 },
      { condition: 'Aortic Emergency', probability: 0.10 },
    ],
    recommended_workup: [
      { test: 'IV Access + Monitoring', priority: 'STAT', rationale: 'Immediate stabilization' },
      { test: 'Basic Metabolic Panel', priority: 'STAT', rationale: 'Electrolytes and renal function' },
    ],
  },
  {
    specialty: 'General Medicine',
    relevance_score: 0.65,
    urgency_score: 0.55,
    confidence: 0.80,
    one_liner: 'Diabetic patient with cardiovascular distress; ensure glycemic control and comprehensive metabolic workup.',
    claims_primary: false,
    flags: [
      { severity: 'INFO', label: 'Diabetic patient', description: 'HbA1c and glucose monitoring needed' },
    ],
    assessment: 'Known diabetic with hypertension presenting with cardiac symptoms. High cardiovascular risk profile. Ensure blood glucose checked, HbA1c for long-term control, and comprehensive metabolic panel. Medication reconciliation important.',
    differentials: [
      { condition: 'Diabetic cardiovascular emergency', probability: 0.30 },
      { condition: 'Metabolic derangement', probability: 0.20 },
    ],
    recommended_workup: [
      { test: 'Blood Glucose', priority: 'STAT', rationale: 'Immediate glycemic status' },
      { test: 'HbA1c', priority: 'ROUTINE', rationale: 'Long-term glycemic control' },
      { test: 'Lipid Panel', priority: 'ROUTINE', rationale: 'Cardiovascular risk assessment' },
    ],
  },
];

export const mockOtherSpecialtyScores = {
  Orthopedics: 0.05,
  Gastroenterology: 0.08,
  Nephrology: 0.22,
  Dermatology: 0.02,
};

export const mockCMOVerdict = {
  patient_id: 'PAT-2024-0042',
  patient_name: 'Lakshmi Devi',
  age: 58,
  gender: 'Female',
  vitals: mockPatientInput.vitals,
  symptoms: mockPatientInput.symptoms,
  medical_history: mockPatientInput.medical_history,
  timestamp: new Date().toISOString(),
  ml_risk_assessment: 'HIGH',
  final_risk_level: 'HIGH',
  risk_adjusted: false,
  priority_score: 82,
  action: 'URGENT',
  primary_department: 'Cardiology',
  secondary_department: 'Emergency Medicine',
  requires_referral: false,
  referral_reason: null,
  explanation: 'Patient presents with acute chest pain accompanied by tachycardia (HR 112), hypertension (168/95), and mild hypoxemia (SpO2 93%). Given her age, diabetic status, and hypertension history, acute coronary syndrome is the leading differential. The specialist council achieved strong consensus on cardiac etiology with supporting pulmonary concerns. Immediate cardiac workup with STAT ECG and troponin is essential.',
  key_factors: [
    'Acute chest pain with tachycardia in a 58-year-old diabetic female',
    'Hypertensive crisis (168/95) with known hypertension',
    'Mild hypoxemia (SpO2 93%) suggesting cardiopulmonary compromise',
    'Multiple cardiovascular risk factors (DM, HTN, age)',
    'Strong specialist consensus on cardiac etiology',
  ],
  safety_alerts: [
    {
      severity: 'CRITICAL',
      source: 'Cardiology',
      label: 'Possible Acute Coronary Syndrome',
      description: 'Chest pain with tachycardia and multiple risk factors. STEMI must be ruled out immediately.',
      action_required: 'STAT 12-lead ECG and Troponin within 10 minutes of arrival',
    },
    {
      severity: 'WARNING',
      source: 'Emergency Medicine',
      label: 'Multi-system Involvement',
      description: 'Simultaneous cardiac and respiratory compromise requires coordinated management.',
      action_required: 'Continuous monitoring, IV access, activate chest pain protocol',
    },
  ],
  specialist_opinions: mockSpecialistOpinions,
  other_specialty_scores: mockOtherSpecialtyScores,
  council_consensus: 0.85,
  dissenting_opinions: ['Neurology noted low probability of primary neurological event'],
  consolidated_workup: [
    { test: '12-Lead ECG', priority: 'STAT', ordered_by: ['Cardiology'], rationale: 'Rule out STEMI/NSTEMI' },
    { test: 'Troponin I/T', priority: 'STAT', ordered_by: ['Cardiology'], rationale: 'Cardiac biomarker assessment' },
    { test: 'IV Access + Monitoring', priority: 'STAT', ordered_by: ['Emergency Medicine'], rationale: 'Immediate stabilization' },
    { test: 'ABG Analysis', priority: 'STAT', ordered_by: ['Pulmonology'], rationale: 'Quantify respiratory compromise' },
    { test: 'Blood Glucose', priority: 'STAT', ordered_by: ['General Medicine'], rationale: 'Immediate glycemic status' },
    { test: 'Basic Metabolic Panel', priority: 'STAT', ordered_by: ['Emergency Medicine'], rationale: 'Electrolytes and renal function' },
    { test: 'Chest X-Ray', priority: 'URGENT', ordered_by: ['Cardiology', 'Pulmonology'], rationale: 'Cardiac and pulmonary assessment' },
    { test: 'Complete Blood Count', priority: 'URGENT', ordered_by: ['Cardiology'], rationale: 'Baseline hematology' },
    { test: 'D-Dimer', priority: 'URGENT', ordered_by: ['Pulmonology'], rationale: 'Rule out PE' },
    { test: 'Neurological examination', priority: 'URGENT', ordered_by: ['Neurology'], rationale: 'Assess for focal deficits' },
    { test: 'HbA1c', priority: 'ROUTINE', ordered_by: ['General Medicine'], rationale: 'Long-term glycemic control' },
    { test: 'Lipid Panel', priority: 'ROUTINE', ordered_by: ['General Medicine'], rationale: 'Cardiovascular risk assessment' },
  ],
};

const makePatient = (id, name, age, gender, risk, priority, action, dept, symptoms, alerts, minutesAgo) => ({
  patient_id: id,
  patient_name: name,
  age,
  gender,
  final_risk_level: risk,
  priority_score: priority,
  action,
  primary_department: dept,
  secondary_department: null,
  symptoms,
  safety_alerts: alerts,
  timestamp: new Date(Date.now() - minutesAgo * 60000).toISOString(),
  vitals: {
    heart_rate: 60 + Math.floor(Math.random() * 60),
    blood_pressure_systolic: 110 + Math.floor(Math.random() * 70),
    blood_pressure_diastolic: 60 + Math.floor(Math.random() * 40),
    temperature: 36.5 + Math.random() * 2,
    spo2: 90 + Math.floor(Math.random() * 10),
  },
  specialist_opinions: mockSpecialistOpinions,
  other_specialty_scores: mockOtherSpecialtyScores,
  council_consensus: 0.75 + Math.random() * 0.2,
  dissenting_opinions: [],
  consolidated_workup: mockCMOVerdict.consolidated_workup,
  explanation: `Patient ${name} triaged with ${risk} risk. Primary concern: ${dept}.`,
  key_factors: [`${symptoms[0]} presentation`, `Age ${age} ${gender}`],
  ml_risk_assessment: risk,
  risk_adjusted: false,
  requires_referral: risk === 'CRITICAL',
  referral_reason: risk === 'CRITICAL' ? 'Requires tertiary care' : null,
  medical_history: [],
});

export const mockPatientQueue = [
  { ...mockCMOVerdict },
  makePatient('PAT-2024-0038', 'Rajesh Kumar', 45, 'Male', 'CRITICAL', 95, 'IMMEDIATE', 'Emergency Medicine',
    ['Severe chest pain', 'Loss of consciousness'],
    [{ severity: 'CRITICAL', source: 'Emergency Medicine', label: 'Cardiac Arrest Risk', description: 'Syncope with chest pain', action_required: 'Immediate resuscitation standby' }], 5),
  makePatient('PAT-2024-0039', 'Priya Sharma', 32, 'Female', 'MEDIUM', 45, 'STANDARD', 'General Medicine',
    ['Fever', 'Cough', 'Fatigue'],
    [], 30),
  makePatient('PAT-2024-0040', 'Arun Patel', 67, 'Male', 'HIGH', 78, 'URGENT', 'Cardiology',
    ['Palpitations', 'Shortness of breath'],
    [{ severity: 'WARNING', source: 'Cardiology', label: 'Arrhythmia suspected', description: 'Irregular palpitations in elderly', action_required: 'ECG monitoring' }], 15),
  makePatient('PAT-2024-0041', 'Meena Devi', 72, 'Female', 'HIGH', 74, 'URGENT', 'Neurology',
    ['Headache', 'Confusion', 'Weakness'],
    [{ severity: 'WARNING', source: 'Neurology', label: 'Stroke concern', description: 'Sudden onset confusion with weakness', action_required: 'CT scan within 30 minutes' }], 20),
  makePatient('PAT-2024-0043', 'Suresh Reddy', 55, 'Male', 'LOW', 25, 'CAN WAIT', 'General Medicine',
    ['Back pain', 'Fatigue'],
    [], 60),
  makePatient('PAT-2024-0044', 'Anjali Gupta', 28, 'Female', 'LOW', 20, 'CAN WAIT', 'General Medicine',
    ['Nausea', 'Abdominal pain'],
    [], 90),
  makePatient('PAT-2024-0045', 'Vikram Singh', 61, 'Male', 'MEDIUM', 52, 'STANDARD', 'Pulmonology',
    ['Wheezing', 'Cough', 'Shortness of breath'],
    [{ severity: 'INFO', source: 'Pulmonology', label: 'COPD History', description: 'Known COPD patient', action_required: 'Nebulization if SpO2 drops' }], 45),
];

export const mockDashboardStats = {
  totalPatientsToday: 24,
  highCriticalCount: 8,
  avgPriorityScore: 56,
  referralsMade: 3,
  riskDistribution: [
    { name: 'Critical', value: 3, color: '#D32F2F' },
    { name: 'High', value: 5, color: '#F57C00' },
    { name: 'Medium', value: 9, color: '#FBC02D' },
    { name: 'Low', value: 7, color: '#388E3C' },
  ],
  departmentLoad: [
    { department: 'Emergency Medicine', count: 6 },
    { department: 'Cardiology', count: 5 },
    { department: 'General Medicine', count: 5 },
    { department: 'Neurology', count: 3 },
    { department: 'Pulmonology', count: 3 },
    { department: 'Orthopedics', count: 2 },
  ],
  dailyTrend: [
    { hour: '8AM', critical: 0, high: 1, medium: 2, low: 1 },
    { hour: '9AM', critical: 1, high: 1, medium: 1, low: 2 },
    { hour: '10AM', critical: 0, high: 2, medium: 2, low: 1 },
    { hour: '11AM', critical: 1, high: 0, medium: 1, low: 1 },
    { hour: '12PM', critical: 0, high: 1, medium: 2, low: 0 },
    { hour: '1PM', critical: 1, high: 1, medium: 1, low: 2 },
  ],
  alertFrequency: [
    { type: 'Critical Alerts', critical: 4, warning: 0, info: 0 },
    { type: 'Warning Alerts', critical: 0, warning: 8, info: 0 },
    { type: 'Info Alerts', critical: 0, warning: 0, info: 6 },
  ],
  specialistEngagement: [
    { specialist: 'Cardiology', avgRelevance: 0.82 },
    { specialist: 'Emergency Med', avgRelevance: 0.78 },
    { specialist: 'Pulmonology', avgRelevance: 0.61 },
    { specialist: 'General Med', avgRelevance: 0.58 },
    { specialist: 'Neurology', avgRelevance: 0.45 },
  ],
};

export const mockSSEEvents = [
  { delay: 500, event: { type: 'status', data: { phase: 'classification', status: 'started', message: 'Analyzing patient vitals and symptoms...' } } },
  { delay: 1500, event: { type: 'classification_result', data: mockClassificationResult } },
  { delay: 500, event: { type: 'status', data: { phase: 'specialist_council', status: 'started', message: 'Convening specialist council...' } } },
  ...mockSpecialistOpinions.map((op, i) => ({
    delay: 500,
    event: { type: 'specialist_opinion', data: op },
  })),
  { delay: 500, event: { type: 'status', data: { phase: 'cmo_synthesis', status: 'started', message: 'CMO synthesizing final verdict...' } } },
  { delay: 1500, event: { type: 'cmo_verdict', data: mockCMOVerdict } },
  { delay: 300, event: { type: 'complete', data: { message: 'Triage complete' } } },
];
